title: TUM Albanian Student Society
email: tumalbaniansociety@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Connecting Albanian students at Technical University of Munich. We foster cultural exchange, academic excellence, and lasting friendships.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tum-albanian-students.github.io" # the base hostname & protocol for your site, e.g. http://example.com
domain: tum-albanian-students.github.io
# Social Media
github_username:  tum-albanian-students


# Build settings
# theme: minima  # Removed - using custom layout
plugins:
  - jekyll-feed
  - jekyll-sass-converter

sass:
  sass_dir: assets
  style: compressed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  members:
    output: true
    permalink: /members/:name

header_pages:
  - about.md
  - blog.md
  - members.md